// Feature: ai-adaptive-features, Property 1: Speed recommendation respects user WPM boundaries
import * as fc from 'fast-check'
import mongoose from 'mongoose'
import { generateSpeedRecommendation } from '../services/ml/speedController'
import ReadingSession, { IReadingSession } from '../models/ReadingSession'
import SpeedRecommendation from '../models/SpeedRecommendation'
import User from '../models/User'
import Book from '../models/Book'

/**
 * Validates: Requirements 1.9
 *
 * Property 1: Speed recommendation respects user WPM boundaries
 * For any user with configured minWPM and maxWPM boundaries, all speed
 * recommendations generated by the AI_Speed_Controller must fall within
 * the range [minWPM, maxWPM], regardless of the calculated recommendation.
 */

// Mock the models
jest.mock('../models/ReadingSession')
jest.mock('../models/SpeedRecommendation')
jest.mock('../models/User')
jest.mock('../models/Book')

// Arbitrary: valid MongoDB ObjectId
const objectIdArb = fc
  .hexaString({ minLength: 24, maxLength: 24 })
  .map(s => new mongoose.Types.ObjectId(s))

// Arbitrary: user WPM boundaries (minWPM < maxWPM)
const wpmBoundariesArb = fc
  .tuple(
    fc.integer({ min: 50, max: 500 }),   // minWPM
    fc.integer({ min: 500, max: 2000 })  // maxWPM
  )
  .map(([min, max]) => ({ minWPM: min, maxWPM: max }))

// Arbitrary: current WPM (can be any value to test boundary enforcement)
const currentWPMArb = fc.integer({ min: 50, max: 2000 })

// Arbitrary: text complexity (affects recommendation calculation)
const textComplexityArb = fc.constantFrom('simple', 'medium', 'complex')

// Arbitrary: session characteristics that influence recommendations
const sessionCharacteristicsArb = fc.record({
  hasFlowState: fc.boolean(),
  hasFrequentPausing: fc.boolean(),
  hasHighComplexity: fc.boolean()
})

// Helper: create words array based on complexity
function createWordsForComplexity(complexity: string, count: number = 100): string[] {
  switch (complexity) {
    case 'simple':
      return Array(count).fill('cat')  // 3 chars, avg <= 5
    case 'medium':
      return Array(count).fill('reading')  // 7 chars, avg = 7
    case 'complex':
      return Array(count).fill('extraordinary')  // 13 chars, avg > 7
    default:
      return Array(count).fill('test')
  }
}

// Helper: create pause events for frequent pausing
function createFrequentPauseEvents(): Array<{ wordIndex: number; duration: number }> {
  return [
    { wordIndex: 10, duration: 2500 },
    { wordIndex: 30, duration: 2500 },
    { wordIndex: 50, duration: 2500 },
    { wordIndex: 70, duration: 2500 },
    { wordIndex: 90, duration: 2500 }
  ]
}

// Helper: create session for flow state
function createFlowStateSession(
  userId: mongoose.Types.ObjectId,
  bookId: mongoose.Types.ObjectId,
  currentWPM: number
): any {
  return {
    _id: new mongoose.Types.ObjectId(),
    userId,
    bookId,
    currentWPM,
    lastWordIndex: 100,
    timeSpent: 350,  // >= 300s for flow state
    date: new Date(),
    pauseEvents: [],  // No long pauses
    speedChanges: [
      { wordIndex: 0, oldWPM: currentWPM, newWPM: currentWPM + 5, timestamp: new Date() }
    ],
    averageWordLength: 5,
    complexityScore: 0.5,
    readingVelocity: currentWPM,
    sessionCompleted: true,
    bookCompleted: false
  }
}

describe('SpeedController - Property 1: Speed recommendation respects user WPM boundaries', () => {
  beforeEach(() => {
    jest.clearAllMocks()
  })

  it('all recommendations must respect user minWPM and maxWPM boundaries', async () => {
    await fc.assert(
      fc.asyncProperty(
        objectIdArb,
        objectIdArb,
        wpmBoundariesArb,
        currentWPMArb,
        textComplexityArb,
        sessionCharacteristicsArb,
        async (userId, bookId, boundaries, currentWPM, complexity, characteristics) => {
          // Setup: User has at least 5 sessions (requirement for recommendations)
          (ReadingSession.countDocuments as jest.Mock).mockResolvedValue(10)

          // Setup: User with configured boundaries
          const mockUser = {
            _id: userId,
            minWPM: boundaries.minWPM,
            maxWPM: boundaries.maxWPM
          }
          ;(User.findById as jest.Mock).mockResolvedValue(mockUser)

          // Setup: Book with words matching complexity
          const mockBook = {
            _id: bookId,
            words: createWordsForComplexity(complexity)
          }
          ;(Book.findById as jest.Mock).mockResolvedValue(mockBook)

          // Setup: Mock SpeedRecommendation to capture the recommendation
          let capturedRecommendation: any = null
          ;(SpeedRecommendation as any).mockImplementation((data: any) => {
            capturedRecommendation = data
            return {
              save: jest.fn().mockResolvedValue(data)
            }
          })

          // Create session based on characteristics
          let session: any

          if (characteristics.hasFlowState) {
            session = createFlowStateSession(userId, bookId, currentWPM)
          } else if (characteristics.hasFrequentPausing) {
            session = {
              _id: new mongoose.Types.ObjectId(),
              userId,
              bookId,
              currentWPM,
              lastWordIndex: 100,
              timeSpent: 200,
              date: new Date(),
              pauseEvents: createFrequentPauseEvents(),
              speedChanges: [],
              averageWordLength: 5,
              complexityScore: 0.5,
              readingVelocity: currentWPM,
              sessionCompleted: true,
              bookCompleted: false
            }
          } else {
            session = {
              _id: new mongoose.Types.ObjectId(),
              userId,
              bookId,
              currentWPM,
              lastWordIndex: 100,
              timeSpent: 200,
              date: new Date(),
              pauseEvents: [],
              speedChanges: [],
              averageWordLength: 5,
              complexityScore: 0.5,
              readingVelocity: currentWPM,
              sessionCompleted: true,
              bookCompleted: false
            }
          }

          // Execute: Generate speed recommendation
          const result = await generateSpeedRecommendation(userId, session)

          // Assert: If a recommendation was generated, it must respect boundaries
          if (result !== null && capturedRecommendation !== null) {
            const recommendedWPM = capturedRecommendation.recommendedWPM

            // Property: recommendedWPM must be within [minWPM, maxWPM]
            expect(recommendedWPM).toBeGreaterThanOrEqual(boundaries.minWPM)
            expect(recommendedWPM).toBeLessThanOrEqual(boundaries.maxWPM)

            // Additional invariant: recommendedWPM must be a positive integer
            expect(recommendedWPM).toBeGreaterThan(0)
            expect(Number.isInteger(recommendedWPM)).toBe(true)
          }
        }
      ),
      { numRuns: 100 }
    )
  })

  it('recommendations at boundary edges are clamped correctly', async () => {
    await fc.assert(
      fc.asyncProperty(
        objectIdArb,
        objectIdArb,
        wpmBoundariesArb,
        async (userId, bookId, boundaries) => {
          // Setup: User has at least 5 sessions
          (ReadingSession.countDocuments as jest.Mock).mockResolvedValue(10)

          // Setup: User with configured boundaries
          const mockUser = {
            _id: userId,
            minWPM: boundaries.minWPM,
            maxWPM: boundaries.maxWPM
          }
          ;(User.findById as jest.Mock).mockResolvedValue(mockUser)

          // Setup: Book with high complexity words (will trigger 15% reduction)
          const mockBook = {
            _id: bookId,
            words: createWordsForComplexity('complex')
          }
          ;(Book.findById as jest.Mock).mockResolvedValue(mockBook)

          // Setup: Mock SpeedRecommendation
          let capturedRecommendation: any = null
          ;(SpeedRecommendation as any).mockImplementation((data: any) => {
            capturedRecommendation = data
            return {
              save: jest.fn().mockResolvedValue(data)
            }
          })

          // Test case 1: Current WPM is very low, reduction would go below minWPM
          const lowWPM = boundaries.minWPM + 10
          const sessionLow: any = {
            _id: new mongoose.Types.ObjectId(),
            userId,
            bookId,
            currentWPM: lowWPM,
            lastWordIndex: 100,
            timeSpent: 200,
            date: new Date(),
            pauseEvents: [],
            speedChanges: [],
            averageWordLength: 5,
            complexityScore: 0.5,
            readingVelocity: lowWPM,
            sessionCompleted: true,
            bookCompleted: false
          }

          await generateSpeedRecommendation(userId, sessionLow)

          if (capturedRecommendation !== null) {
            // Should be clamped to minWPM
            expect(capturedRecommendation.recommendedWPM).toBeGreaterThanOrEqual(boundaries.minWPM)
          }

          // Reset
          capturedRecommendation = null

          // Test case 2: Current WPM is very high, increase would go above maxWPM
          const highWPM = boundaries.maxWPM - 10
          const sessionHigh = createFlowStateSession(userId, bookId, highWPM)

          await generateSpeedRecommendation(userId, sessionHigh)

          if (capturedRecommendation !== null) {
            // Should be clamped to maxWPM
            expect(capturedRecommendation.recommendedWPM).toBeLessThanOrEqual(boundaries.maxWPM)
          }
        }
      ),
      { numRuns: 100 }
    )
  })

  it('boundary enforcement works with extreme user configurations', async () => {
    await fc.assert(
      fc.asyncProperty(
        objectIdArb,
        objectIdArb,
        currentWPMArb,
        async (userId, bookId, currentWPM) => {
          // Setup: User has at least 5 sessions
          (ReadingSession.countDocuments as jest.Mock).mockResolvedValue(10)

          // Test extreme boundaries
          const extremeBoundaries = [
            { minWPM: 50, maxWPM: 100 },     // Very narrow range
            { minWPM: 100, maxWPM: 1000 },   // Default range
            { minWPM: 500, maxWPM: 2000 },   // High speed range
            { minWPM: 200, maxWPM: 200 }     // Single value (edge case)
          ]

          for (const boundaries of extremeBoundaries) {
            // Setup: User with extreme boundaries
            const mockUser = {
              _id: userId,
              minWPM: boundaries.minWPM,
              maxWPM: boundaries.maxWPM
            }
            ;(User.findById as jest.Mock).mockResolvedValue(mockUser)

            // Setup: Book with complex text
            const mockBook = {
              _id: bookId,
              words: createWordsForComplexity('complex')
            }
            ;(Book.findById as jest.Mock).mockResolvedValue(mockBook)

            // Setup: Mock SpeedRecommendation
            let capturedRecommendation: any = null
            ;(SpeedRecommendation as any).mockImplementation((data: any) => {
              capturedRecommendation = data
              return {
                save: jest.fn().mockResolvedValue(data)
              }
            })

            // Create session
            const session: any = {
              _id: new mongoose.Types.ObjectId(),
              userId,
              bookId,
              currentWPM,
              lastWordIndex: 100,
              timeSpent: 200,
              date: new Date(),
              pauseEvents: [],
              speedChanges: [],
              averageWordLength: 5,
              complexityScore: 0.5,
              readingVelocity: currentWPM,
              sessionCompleted: true,
              bookCompleted: false
            }

            // Execute
            await generateSpeedRecommendation(userId, session)

            // Assert: If recommendation generated, must respect boundaries
            if (capturedRecommendation !== null) {
              expect(capturedRecommendation.recommendedWPM).toBeGreaterThanOrEqual(boundaries.minWPM)
              expect(capturedRecommendation.recommendedWPM).toBeLessThanOrEqual(boundaries.maxWPM)
            }
          }
        }
      ),
      { numRuns: 100 }
    )
  })
})
